# Edit the BuildOptions.cmake file to change build time options
INCLUDE(BuildOptions.cmake)

CMAKE_MINIMUM_REQUIRED(VERSION ${CMAKE_MINIMUM_REQUIRED_VERSION})

# set the C++ standard to C++ 20
SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)
SET(CMAKE_CXX_EXTENSIONS OFF)

PROJECT(${MAIN_PROJECT_NAME} LANGUAGES CXX)

# load package
FIND_PACKAGE(directxtex CONFIG REQUIRED)
FIND_PACKAGE(imgui CONFIG REQUIRED)

# compile libs
ADD_SUBDIRECTORY(engine/utils)

# compile shaders
ADD_SUBDIRECTORY(shader)

# compile exe
ADD_SUBDIRECTORY(engine)

# sort compile
ADD_DEPENDENCIES(${MAIN_PROJECT_NAME} utils)
ADD_DEPENDENCIES(${MAIN_PROJECT_NAME} shaders)

TARGET_LINK_LIBRARIES(${MAIN_PROJECT_NAME} PRIVATE imgui::imgui Microsoft::DirectXTex)
TARGET_LINK_LIBRARIES(${MAIN_PROJECT_NAME} PRIVATE utils)

# define macros
IF (ENABLE_NOTIFICATION_ICON)
    ADD_COMPILE_DEFINITIONS(_ENABLE_NOTIFICATION_ICON)
ENDIF ()

IF (SINGLE_INSTANCE_ONLY)
    ADD_COMPILE_DEFINITIONS(_SINGLE_INSTANCE_ONLY)
ENDIF ()

